### ISSUE TITLE
Forming a lexicographically ordered list of encrypted values

### ISSUE THREAD

**Issue by xpepermint** [cipherstash/ore.rs#38]
I'm so glad you guys are working on this! Looks great! I'm struggling with a question regarding the lexicographical ordering of encrypted values to which you might have an answer.

Suppose you are adding values in a structure that automatically orders them in a lexicographical fashion. Think of b-tree indexed structure or something.

```
ADD "b"
ADD "a"
ADD "d"
ADD "c"
```

Iterating through such list would return an ordered array like this:

```
["a", "b", "c", "d"]
```

Now, let's repeat these steps but this time `ADD` ORE encrypted values. This new list won't be ordered anymore. We can sort it by scrolling through the list and `compare` each entry. Obviously, this solution won't work for long lists or database indexes where you'd like to just stream data without any processing.

I wonder is there a way to generate ORE encoded values in a way that their byte-representations would still form an ordered list? I believe that just computing a "comparing" of `left` and `right` part of the ORE encrypted value won't do the trick. Also, I think that the `left` part should not even be stored in the database, right?

I'd appreciate any suggestion on this. Thank you.

**Comment by mpalmer** [comment]
> This new list won't be ordered anymore. We can sort it by scrolling through the list and compare each entry. Obviously, this solution won't work for long lists or database indexes where you'd like to just stream data without any processing.

The key to making such a process work is to insert the new value into the list by comparing the new value to the existing values (using the ORE comparison function), and then inserting the new value into the appropriate ordered location -- exactly how a b-tree (or similar) already works.  Then walking the tree (or other ordered data structure) gives you the values in order, automagically.

> I wonder is there a way to generate ORE encoded values in a way that their byte-representations would still form an ordered list?

That form of encryption is typically referred to as "Order-Preserving Encryption", and there's proofs available that show that you can't get reasonable security from such a scheme in polynomial space.

> Also, I think that the left part should not even be stored in the database, right?

Yes, to maintain IND-CPA security of the snapshot, you should not store left ciphertexts.  This isn't possible in ore.rs at present, though, if you want to be able to fully order a group of ciphertexts.

**Comment by xpepermint** [comment]
Thanks @mpalmer for the reply.

> The key to making such a process work is to insert the new value into the list by comparing the new value to the existing values (using the ORE comparison function), and then inserting the new value into the appropriate ordered location -- exactly how a b-tree (or similar) already works. Then walking the tree (or other ordered data structure) gives you the values in order, automagically.

What I meant is that `CipherText.to_bytes` will return `left` and `right` or a merged version of the two in bytes. These bytes do not represent any order and I still need to create `CipherText::from_bytes` to be able to do the comparison. So, I guess it's not possible and I assume it wouldn't be safe if that was the case.

> Yes, to maintain IND-CPA security of the snapshot, you should not store left ciphertexts. This isn't possible in ore.rs at present, though, if you want to be able to fully order a group of ciphertexts.

I see. So the only way currently is to use `BTreeMap` and insert items like `.insert(MyKey(left_and_right), value)`, where `MyIndex` implements `Ord`. Right?

**Comment by mpalmer** [comment]
> What I meant is that CipherText.to_bytes will return left and right or a merged version of the two in bytes. These bytes do not represent any order and I still need to create CipherText::from_bytes to be able to do the comparison. So, I guess it's not possible and I assume it wouldn't be safe if that was the case.

Ah, I think I see what you mean.  The serialized form of an ORE ciphertext cannot be compared directly using a "standard" comparison operator; you need *some* sort of custom code to do the comparison and determine the result.  That isn't a limitation of ore.rs; it's a fundamental restriction required to avoid the security problems inherent in efficient Order-Preserving Encryption schemes.

If you can hook back into Rust, you can deserialize the ciphertexts (with `CipherText::from_bytes`) and then do the comparison on the resulting Rust structs.  A Lewi-Wu ciphertext comparison isn't particularly complicated, if you can't hook into Rust and need to do it in another language -- [compare_raw_slices](https://github.com/cipherstash/ore.rs/blob/main/src/scheme/bit2.rs#L177) shows how it can be done with serialized ciphertexts, if you needed to port it to another language.

However, if you're limited to some existing codebase's idea of what constitutes comparisons, then yes, you are rather out of luck.

> So the only way currently is to use BTreeMap and insert items like .insert(MyKey(left_and_right), value), where MyIndex implements Ord. Right?

Yes, that sounds about right.

**Comment by xpepermint** [comment]
I think you clarified my questions nicely.
Thank you for your effort.
