### ISSUE TITLE
is there any api for batch processing?

### ISSUE THREAD

**Issue by lidh15** [cipherstash/ore.rs#52]
what are the best practices when I need to compare a value with a vector of value or compare between two vectors with the same length?

**Comment by coderdan** [comment]
The ciphertexts encrypted by the `encrypt` method implement `PartialOrd` so you can compare them with the standard operators (e.g. `==` and `>`). For example, to filter a vector or ORE encrypted values you can do the following:

```rust
fn main() {
    let k1: [u8; 16] = hex!("00010203 04050607 08090a0b 0c0d0e0f");
    let k2: [u8; 16] = hex!("00010203 04050607 08090a0b 0c0d0e0f");
    let ore: OREAES128 = ORECipher::init(&k1, &k2).unwrap();

    let a = 200u64.encrypt(&ore).unwrap();

    let list = vec![123u64, 456u64, 789u64]
        .iter()
        .map(|x| x.encrypt(&ore).unwrap())
        .collect::<Vec<_>>();

    for result in list.iter().filter(|&x| x < &a) {
        println!("{result:?}");
    }
}
```

Or if you have a second value, you can use a Range:

```rust
for result in list.iter().filter(|x| (&a..&b).contains(x)) {
    println!("{result:?}");
}
```

**Comment by lidh15** [comment]
Okay, thank you
