### ISSUE TITLE
is there any api for serde?

### ISSUE THREAD

**Issue by lidh15** [cipherstash/ore.rs#53]
like I need to send the ciphertext to somewhere else, hopefully via http, so I wish the ciphertext to be json serializable and de serializable.
is there any way to do this?

**Comment by bennetthardwick** [comment]
Hey @lidh15, the CipherText API has a `to_bytes` and `from_bytes` that can be used for serialisation and deserliasation. You could take the binary output from that and convert it to a base64 encoded string which can be included in your json.

Unfortunately there is no direct support for serde at the moment.

**Comment by lidh15** [comment]
thank you
